/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { AuditLogFindManyArgs } from "../../auditLog/base/AuditLogFindManyArgs";
import { AuditLog } from "../../auditLog/base/AuditLog";
import { AuditLogWhereUniqueInput } from "../../auditLog/base/AuditLogWhereUniqueInput";
import { PasswordEntryFindManyArgs } from "../../passwordEntry/base/PasswordEntryFindManyArgs";
import { PasswordEntry } from "../../passwordEntry/base/PasswordEntry";
import { PasswordEntryWhereUniqueInput } from "../../passwordEntry/base/PasswordEntryWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        password: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          password: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          password: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/auditLogs")
  @ApiNestedQuery(AuditLogFindManyArgs)
  async findAuditLogs(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<AuditLog[]> {
    const query = plainToClass(AuditLogFindManyArgs, request.query);
    const results = await this.service.findAuditLogs(params.id, {
      ...query,
      select: {
        action: true,
        createdAt: true,
        entityId: true,
        entityName: true,
        id: true,
        timestamp: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/auditLogs")
  async connectAuditLogs(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuditLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auditLogs: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/auditLogs")
  async updateAuditLogs(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuditLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auditLogs: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/auditLogs")
  async disconnectAuditLogs(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuditLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auditLogs: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/passwordEntries")
  @ApiNestedQuery(PasswordEntryFindManyArgs)
  async findPasswordEntries(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<PasswordEntry[]> {
    const query = plainToClass(PasswordEntryFindManyArgs, request.query);
    const results = await this.service.findPasswordEntries(params.id, {
      ...query,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        notes: true,
        password: true,
        title: true,
        updatedAt: true,
        url: true,

        user: {
          select: {
            id: true,
          },
        },

        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/passwordEntries")
  async connectPasswordEntries(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PasswordEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      passwordEntries: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/passwordEntries")
  async updatePasswordEntries(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PasswordEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      passwordEntries: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/passwordEntries")
  async disconnectPasswordEntries(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: PasswordEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      passwordEntries: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
